name: Build and test

on:
  push:
  pull_request:
    types: [ready_for_review]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16', '18', '20' ]
    name: Test / node v${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node }}
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build        
